version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}?schema=public
    volumes:
      - ./src:/app/src
    command: npm run start:dev
    ports:
      - '4000:3000'
    depends_on:
      - db
    container_name: backend
  db:
    image: postgres:16
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - poc-db-data:/var/lib/postgresql/data
    container_name: db

volumes:
  poc-db-data: